// Package db provides read-only access to the shared SQLite database produced
// by the Python analysis pipeline. The Go server only reads data; all writes
// are done by the Python side except for chat history and profile updates.
package db

import (
	"database/sql"
	"log"
	"os"
	"path/filepath"
	"time"

	_ "github.com/mattn/go-sqlite3"
)

// ─────────────────────────────────────────────────────────
// Domain types
// ─────────────────────────────────────────────────────────

// Stock represents a registered stock (holding or watchlist).
type Stock struct {
	ID            int64
	Ticker        string
	Name          string
	Market        string
	Category      string
	PurchasePrice float64
	PurchaseDate  string
	CreatedAt     string
}

// DailyReport holds the Claude-generated analysis for one stock on one day.
type DailyReport struct {
	ID                 int64
	Ticker             string
	ReportDate         string
	Price              float64
	PriceChangePct     float64
	Signal             string
	Confidence         int
	Reason             string
	TargetPrice        float64
	StopLoss           float64
	RecommendedAmount  float64
	RecommendedShares  int
	RSI                float64
	MA20               float64
	MA50               float64
	MA200              float64
	MACD               float64
	BusinessSummaryJa  string
	RawAnalysis        string
	CreatedAt          string
}

// NewsItem stores a single news article linked to a stock (or macro).
type NewsItem struct {
	ID          int64
	Ticker      string
	Title       string
	Summary     string
	Sentiment   string
	Source      string
	URL         string
	PublishedAt string
	ReportDate  string
}

// DailyInsight is the educational "insight corner" generated by Claude.
type DailyInsight struct {
	ID                int64
	ReportDate        string
	Headline          string
	Explanation       string
	ImpactOnHoldings  string
	Keyword           string
	KeywordExplanation string
	RelatedTickers    string
}

// ChatMessage is one turn in the per-ticker chat history.
type ChatMessage struct {
	Role      string
	Content   string
	CreatedAt string
}

// UserProfile holds the user's investment settings.
type UserProfile struct {
	ID         int64
	Style      string
	LineUserID string
	UpdatedAt  string
}

// ─────────────────────────────────────────────────────────
// Connection
// ─────────────────────────────────────────────────────────

// Open opens (or creates) the SQLite database at the given path.
// Caller is responsible for calling Close().
func Open(dbPath string) *sql.DB {
	if err := os.MkdirAll(filepath.Dir(dbPath), 0o755); err != nil {
		log.Fatalf("db: cannot create data dir: %v", err)
	}
	conn, err := sql.Open("sqlite3", dbPath+"?_journal_mode=WAL&_foreign_keys=on")
	if err != nil {
		log.Fatalf("db: open error: %v", err)
	}
	conn.SetMaxOpenConns(1) // SQLite supports only one writer at a time
	return conn
}

// ─────────────────────────────────────────────────────────
// stocks
// ─────────────────────────────────────────────────────────

// GetAllStocks returns all stocks ordered by category then ticker.
func GetAllStocks(db *sql.DB) ([]Stock, error) {
	rows, err := db.Query(
		"SELECT id, ticker, name, market, category, COALESCE(purchase_price,0), COALESCE(purchase_date,''), created_at FROM stocks ORDER BY category, market, ticker",
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var stocks []Stock
	for rows.Next() {
		var s Stock
		if err := rows.Scan(&s.ID, &s.Ticker, &s.Name, &s.Market, &s.Category,
			&s.PurchasePrice, &s.PurchaseDate, &s.CreatedAt); err != nil {
			return nil, err
		}
		stocks = append(stocks, s)
	}
	return stocks, rows.Err()
}

// GetStock returns a single stock by ticker, or nil if not found.
func GetStock(db *sql.DB, ticker string) (*Stock, error) {
	row := db.QueryRow(
		"SELECT id, ticker, name, market, category, COALESCE(purchase_price,0), COALESCE(purchase_date,''), created_at FROM stocks WHERE ticker = ?",
		ticker,
	)
	var s Stock
	err := row.Scan(&s.ID, &s.Ticker, &s.Name, &s.Market, &s.Category,
		&s.PurchasePrice, &s.PurchaseDate, &s.CreatedAt)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	return &s, err
}

// AddStock inserts or replaces a stock record.
func AddStock(db *sql.DB, s Stock) error {
	_, err := db.Exec(
		`INSERT OR REPLACE INTO stocks (ticker, name, market, category, purchase_price, purchase_date)
		 VALUES (?, ?, ?, ?, ?, ?)`,
		s.Ticker, s.Name, s.Market, s.Category,
		nullFloat(s.PurchasePrice), nullString(s.PurchaseDate),
	)
	return err
}

// DeleteStock removes a stock and its chat history.
func DeleteStock(db *sql.DB, ticker string) error {
	tx, err := db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()
	if _, err := tx.Exec("DELETE FROM stocks WHERE ticker = ?", ticker); err != nil {
		return err
	}
	if _, err := tx.Exec("DELETE FROM chat_history WHERE ticker = ?", ticker); err != nil {
		return err
	}
	return tx.Commit()
}

// ─────────────────────────────────────────────────────────
// daily_reports
// ─────────────────────────────────────────────────────────

// GetLatestReport returns the most recent report for a ticker.
func GetLatestReport(db *sql.DB, ticker string) (*DailyReport, error) {
	row := db.QueryRow(
		`SELECT id, ticker, report_date, COALESCE(price,0), COALESCE(price_change_pct,0),
		        COALESCE(signal,''), COALESCE(confidence,0), COALESCE(reason,''),
		        COALESCE(target_price,0), COALESCE(stop_loss,0),
		        COALESCE(recommended_amount,0), COALESCE(recommended_shares,0),
		        COALESCE(rsi,0), COALESCE(ma20,0), COALESCE(ma50,0), COALESCE(ma200,0),
		        COALESCE(macd,0), COALESCE(business_summary_ja,''), COALESCE(raw_analysis,''),
		        created_at
		 FROM daily_reports WHERE ticker = ?
		 ORDER BY report_date DESC LIMIT 1`,
		ticker,
	)
	var r DailyReport
	err := row.Scan(&r.ID, &r.Ticker, &r.ReportDate, &r.Price, &r.PriceChangePct,
		&r.Signal, &r.Confidence, &r.Reason, &r.TargetPrice, &r.StopLoss,
		&r.RecommendedAmount, &r.RecommendedShares,
		&r.RSI, &r.MA20, &r.MA50, &r.MA200, &r.MACD,
		&r.BusinessSummaryJa, &r.RawAnalysis, &r.CreatedAt)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	return &r, err
}

// GetTodayReports returns all reports with today's date.
func GetTodayReports(db *sql.DB) ([]DailyReport, error) {
	today := time.Now().Format("2006-01-02")
	rows, err := db.Query(
		`SELECT id, ticker, report_date, COALESCE(price,0), COALESCE(price_change_pct,0),
		        COALESCE(signal,''), COALESCE(confidence,0), COALESCE(reason,''),
		        COALESCE(target_price,0), COALESCE(stop_loss,0),
		        COALESCE(recommended_amount,0), COALESCE(recommended_shares,0),
		        COALESCE(rsi,0), COALESCE(ma20,0), COALESCE(ma50,0), COALESCE(ma200,0),
		        COALESCE(macd,0), COALESCE(business_summary_ja,''), COALESCE(raw_analysis,''),
		        created_at
		 FROM daily_reports WHERE report_date = ?`,
		today,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return scanReports(rows)
}

func scanReports(rows *sql.Rows) ([]DailyReport, error) {
	var reports []DailyReport
	for rows.Next() {
		var r DailyReport
		if err := rows.Scan(&r.ID, &r.Ticker, &r.ReportDate, &r.Price, &r.PriceChangePct,
			&r.Signal, &r.Confidence, &r.Reason, &r.TargetPrice, &r.StopLoss,
			&r.RecommendedAmount, &r.RecommendedShares,
			&r.RSI, &r.MA20, &r.MA50, &r.MA200, &r.MACD,
			&r.BusinessSummaryJa, &r.RawAnalysis, &r.CreatedAt); err != nil {
			return nil, err
		}
		reports = append(reports, r)
	}
	return reports, rows.Err()
}

// ─────────────────────────────────────────────────────────
// daily_insights
// ─────────────────────────────────────────────────────────

// GetLatestInsight returns the most recent daily insight.
func GetLatestInsight(db *sql.DB) (*DailyInsight, error) {
	row := db.QueryRow(
		`SELECT id, report_date, COALESCE(headline,''), COALESCE(explanation,''),
		        COALESCE(impact_on_holdings,''), COALESCE(keyword,''),
		        COALESCE(keyword_explanation,''), COALESCE(related_tickers,'')
		 FROM daily_insights ORDER BY report_date DESC LIMIT 1`,
	)
	var d DailyInsight
	err := row.Scan(&d.ID, &d.ReportDate, &d.Headline, &d.Explanation,
		&d.ImpactOnHoldings, &d.Keyword, &d.KeywordExplanation, &d.RelatedTickers)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	return &d, err
}

// ─────────────────────────────────────────────────────────
// chat_history
// ─────────────────────────────────────────────────────────

// GetChatHistory returns up to limit messages for a ticker in chronological order.
func GetChatHistory(db *sql.DB, ticker string, limit int) ([]ChatMessage, error) {
	rows, err := db.Query(
		`SELECT role, content, created_at FROM chat_history
		 WHERE ticker = ? ORDER BY id DESC LIMIT ?`,
		ticker, limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var msgs []ChatMessage
	for rows.Next() {
		var m ChatMessage
		if err := rows.Scan(&m.Role, &m.Content, &m.CreatedAt); err != nil {
			return nil, err
		}
		msgs = append(msgs, m)
	}
	if rows.Err() != nil {
		return nil, rows.Err()
	}
	// Reverse to chronological order
	for i, j := 0, len(msgs)-1; i < j; i, j = i+1, j-1 {
		msgs[i], msgs[j] = msgs[j], msgs[i]
	}
	return msgs, nil
}

// AppendChat saves one chat message to the database.
func AppendChat(db *sql.DB, ticker, role, content string) error {
	_, err := db.Exec(
		"INSERT INTO chat_history (ticker, role, content) VALUES (?, ?, ?)",
		ticker, role, content,
	)
	return err
}

// ClearChatHistory deletes all messages for a ticker.
func ClearChatHistory(db *sql.DB, ticker string) error {
	_, err := db.Exec("DELETE FROM chat_history WHERE ticker = ?", ticker)
	return err
}

// ─────────────────────────────────────────────────────────
// user_profile
// ─────────────────────────────────────────────────────────

// GetProfile returns the single user profile row (id=1).
func GetProfile(db *sql.DB) (*UserProfile, error) {
	row := db.QueryRow(
		`SELECT id, style, COALESCE(line_user_id,''), COALESCE(updated_at,'')
		 FROM user_profile WHERE id = 1`,
	)
	var p UserProfile
	err := row.Scan(&p.ID, &p.Style, &p.LineUserID, &p.UpdatedAt)
	if err == sql.ErrNoRows {
		return &UserProfile{ID: 1, Style: "normal"}, nil
	}
	return &p, err
}

// UpdateProfile overwrites the user profile (id=1).
func UpdateProfile(db *sql.DB, p UserProfile) error {
	_, err := db.Exec(
		`UPDATE user_profile SET style = ?, updated_at = datetime('now') WHERE id = 1`,
		p.Style,
	)
	return err
}

// ─────────────────────────────────────────────────────────
// jp_stocks (JPX listing master)
// ─────────────────────────────────────────────────────────

// JPStock is one row from the jp_stocks table.
type JPStock struct {
	Code    string
	Name    string
	Sector  string
	Market  string
}

// SearchJPStocks searches the local JPX master by name (LIKE) or code prefix.
// Pass a non-empty byName to search by name, or a non-empty byCode to search by code prefix.
func SearchJPStocks(db *sql.DB, byName, byCode string) ([]JPStock, error) {
	var query string
	var args []any

	switch {
	case byName != "" && byCode != "":
		query = `SELECT code, name, sector, market_segment FROM jp_stocks
		         WHERE name LIKE ? OR code LIKE ? ORDER BY code ASC LIMIT 20`
		args = []any{"%" + byName + "%", byCode + "%"}
	case byName != "":
		query = `SELECT code, name, sector, market_segment FROM jp_stocks
		         WHERE name LIKE ? ORDER BY code ASC LIMIT 20`
		args = []any{"%" + byName + "%"}
	case byCode != "":
		query = `SELECT code, name, sector, market_segment FROM jp_stocks
		         WHERE code LIKE ? ORDER BY code ASC LIMIT 20`
		args = []any{byCode + "%"}
	default:
		return nil, nil
	}

	rows, err := db.Query(query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var stocks []JPStock
	for rows.Next() {
		var s JPStock
		if err := rows.Scan(&s.Code, &s.Name, &s.Sector, &s.Market); err != nil {
			return nil, err
		}
		stocks = append(stocks, s)
	}
	return stocks, rows.Err()
}

// ─────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────

func nullFloat(f float64) interface{} {
	if f == 0 {
		return nil
	}
	return f
}

func nullString(s string) interface{} {
	if s == "" {
		return nil
	}
	return s
}
